language: node_js
node_js:
  - "node"
 
sudo: false

before_install:
  - git config --global user.email "libsora25@gmail.com"
  - git config --global user.name "Travis"

install:
  - ./script/install.sh
  
script:
  - ./script/execute.sh

branches:
  only:
    - master

notifications:
  email: false